version: "3"
services:
  proxy:
    image: nginx:1.15.5
    volumes:
      - ./images/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/usr/share/nginx/html/backend
      - ./frontend:/usr/share/nginx/html/frontend
    ports:
      - "80:80"
      - "8080:8080"
  php:
    build: ./images/php-dev
    environment:
      APP_ENV: "dev"
      DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?serverVersion=8"
      MAILER_URL: "smtp://mailcatcher:1025"
    volumes:
      - ./backend:/usr/share/nginx/html/backend
  mysql:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  mailcatcher:
    image: nkowalik/mailcatcher
    ports:
      - "4000:80"
  node:
    image: node:13.6-alpine
    working_dir: /home/node/app
    volumes:
    - ./frontend:/home/node/app
